export type ServiceCategory = "automobiles" | "real-estate" | "other";

export interface Organization {
  id: number;
  name: string;
  city: string;
  services: string[];
  category: ServiceCategory;
  description: string;
  rating: number;
  reviews: number;
  priceFrom: number;
  priceTo: number;
  licensed: boolean;
  years: number;
  responseDays: number;
  availabilityDays: number;
  website: string;
  phone: string;
  tags: string[];
  imageUrl?: string;
}

export const ORGS: Organization[] = [
  {
    id: 1,
    name: "СтройМастер KZ",
    city: "Алматы",
    category: "real-estate",
    description: "Капитальный и косметический ремонт квартир под ключ. Гарантия и договор.",
    services: ["Ремонт под ключ", "Отделка", "Сантехника", "Электрика"],
    rating: 4.8,
    reviews: 214,
    priceFrom: 12000,
    priceTo: 30000,
    licensed: true,
    years: 8,
    responseDays: 1,
    availabilityDays: 5,
    website: "https://demo.example/1",
    phone: "+7 701 123 45 67",
    tags: ["Гарантия 12 мес.", "Без предоплаты"],
    imageUrl: "https://images.unsplash.com/photo-1560185127-6ed189bf02f4",
  },
  {
    id: 2,
    name: "УютДом Про",
    city: "Астана",
    category: "real-estate",
    description: "Дизайн-проект и реализация. Мебель на заказ, визуализации, сопровождение.",
    services: ["Дизайн‑проект", "Ремонт под ключ", "Мебель на заказ"],
    rating: 4.6,
    reviews: 97,
    priceFrom: 15000,
    priceTo: 42000,
    licensed: true,
    years: 5,
    responseDays: 2,
    availabilityDays: 14,
    website: "https://demo.example/2",
    phone: "+7 702 555 77 88",
    tags: ["3D‑визуализация", "Договор"],
    imageUrl: "https://images.unsplash.com/photo-1600585154526-990dced4db0d",
  },
  {
    id: 3,
    name: "ЭлектроСервис",
    city: "Шымкент",
    category: "other",
    description: "Монтаж и ремонт электропроводки, автоматы, щиты, освещение. Срочный выезд.",
    services: ["Электрика"],
    rating: 4.2,
    reviews: 53,
    priceFrom: 8000,
    priceTo: 20000,
    licensed: false,
    years: 3,
    responseDays: 1,
    availabilityDays: 3,
    website: "https://demo.example/3",
    phone: "+7 705 222 11 00",
    tags: ["Срочный выезд"],
    imageUrl: "https://images.unsplash.com/photo-1516116216624-53e697fedbea",
  },
  {
    id: 4,
    name: "СантехЛюкс",
    city: "Алматы",
    category: "other",
    description: "Сантехнические работы любой сложности. Установка, замена, ремонт. 24/7.",
    services: ["Сантехника"],
    rating: 4.9,
    reviews: 341,
    priceFrom: 10000,
    priceTo: 25000,
    licensed: true,
    years: 10,
    responseDays: 1,
    availabilityDays: 2,
    website: "https://demo.example/4",
    phone: "+7 700 999 66 55",
    tags: ["24/7", "Гарантия 24 мес."],
    imageUrl: "https://images.unsplash.com/photo-1581090467213-8cba0e09a49a",
  },
  {
    id: 5,
    name: "Окна&Двери KZ",
    city: "Актобе",
    category: "real-estate",
    description: "ПВХ и алюминиевые конструкции. Замер бесплатно, рассрочка, гарантия.",
    services: ["Окна и двери", "Отделка"],
    rating: 4.3,
    reviews: 61,
    priceFrom: 9000,
    priceTo: 38000,
    licensed: true,
    years: 4,
    responseDays: 3,
    availabilityDays: 7,
    website: "https://demo.example/5",
    phone: "+7 707 123 00 11",
    tags: ["Рассрочка", "Замер бесплатно"],
    imageUrl: "https://images.unsplash.com/photo-1581093588401-16e7c98a8f17",
  },
  {
    id: 6,
    name: "AutoPro Сервис",
    city: "Алматы",
    category: "automobiles",
    description: "Техобслуживание, диагностика, ремонт ходовой и тормозной системы.",
    services: ["ТО", "Диагностика", "Ходовая"],
    rating: 4.5,
    reviews: 188,
    priceFrom: 7000,
    priceTo: 35000,
    licensed: true,
    years: 6,
    responseDays: 1,
    availabilityDays: 3,
    website: "https://demo.example/auto1",
    phone: "+7 701 100 20 30",
    tags: ["Гарантия", "Оригинальные запчасти"],
    imageUrl: "https://images.unsplash.com/photo-1515920010264-05a0f6a4c28f",
  },
  {
    id: 7,
    name: "Detailing KZ",
    city: "Астана",
    category: "automobiles",
    description: "Детейлинг, полировка, керамика, химчистка салона.",
    services: ["Детейлинг", "Полировка", "Керамика"],
    rating: 4.7,
    reviews: 132,
    priceFrom: 15000,
    priceTo: 80000,
    licensed: false,
    years: 4,
    responseDays: 2,
    availabilityDays: 5,
    website: "https://demo.example/auto2",
    phone: "+7 702 300 40 50",
    tags: ["Запись онлайн"],
    imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70",
  },
  {
    id: 8,
    name: "Шиномонтаж 24",
    city: "Караганда",
    category: "automobiles",
    description: "Шиномонтаж, балансировка, сезонная смена колес 24/7.",
    services: ["Шиномонтаж", "Балансировка"],
    rating: 4.1,
    reviews: 79,
    priceFrom: 3000,
    priceTo: 15000,
    licensed: false,
    years: 7,
    responseDays: 0,
    availabilityDays: 0,
    website: "https://demo.example/auto3",
    phone: "+7 705 555 55 55",
    tags: ["24/7"],
    imageUrl: "https://images.unsplash.com/photo-1515920010264-05a0f6a4c28f",
  },
  {
    id: 9,
    name: "РемТехника",
    city: "Атырау",
    category: "other",
    description: "Ремонт бытовой техники: стиральные машины, холодильники, плиты.",
    services: ["Техника"],
    rating: 4.4,
    reviews: 65,
    priceFrom: 6000,
    priceTo: 28000,
    licensed: false,
    years: 5,
    responseDays: 1,
    availabilityDays: 2,
    website: "https://demo.example/oth1",
    phone: "+7 700 800 90 10",
    tags: ["Выезд"],
    imageUrl: "https://images.unsplash.com/photo-1581093588401-16e7c98a8f17",
  },
  {
    id: 10,
    name: "Мастер Мебели",
    city: "Костанай",
    category: "other",
    description: "Сборка и ремонт мебели, регулировка фурнитуры, изготовление деталей.",
    services: ["Мебель"],
    rating: 4.0,
    reviews: 41,
    priceFrom: 5000,
    priceTo: 25000,
    licensed: false,
    years: 3,
    responseDays: 2,
    availabilityDays: 4,
    website: "https://demo.example/oth2",
    phone: "+7 700 700 70 70",
    tags: ["Недорого"],
    imageUrl: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
  },
  {
    id: 11,
    name: "CleanUp Pro",
    city: "Алматы",
    category: "real-estate",
    description: "Клининг квартир и домов, генеральная уборка, после ремонта.",
    services: ["Клининг"],
    rating: 4.6,
    reviews: 112,
    priceFrom: 10000,
    priceTo: 40000,
    licensed: true,
    years: 5,
    responseDays: 1,
    availabilityDays: 2,
    website: "https://demo.example/re1",
    phone: "+7 777 111 22 33",
    tags: ["Эко-средства"],
    imageUrl: "https://images.unsplash.com/photo-1600585154526-990dced4db0d",
  },
  // --- Additional real-estate to reach >=10 ---
  {
    id: 12,
    name: "ДомСтрой Эксперт",
    city: "Алматы",
    category: "real-estate",
    description: "Ремонт домов и коттеджей под ключ, инженерные сети.",
    services: ["Ремонт под ключ", "Электрика", "Сантехника"],
    rating: 4.7,
    reviews: 88,
    priceFrom: 14000,
    priceTo: 38000,
    licensed: true,
    years: 9,
    responseDays: 1,
    availabilityDays: 7,
    website: "https://example.com/re2",
    phone: "+7 777 200 30 40",
    tags: ["Гарантия", "Договор"],
    imageUrl: "https://images.unsplash.com/photo-1600585154526-990dced4db0d",
  },
  {
    id: 13,
    name: "Квартира+",
    city: "Астана",
    category: "real-estate",
    description: "Косметический ремонт под ключ, быстрые сроки.",
    services: ["Ремонт под ключ", "Отделка"],
    rating: 4.3,
    reviews: 56,
    priceFrom: 11000,
    priceTo: 26000,
    licensed: true,
    years: 6,
    responseDays: 2,
    availabilityDays: 10,
    website: "https://example.com/re3",
    phone: "+7 777 300 11 22",
    tags: ["Быстро"],
    imageUrl: "https://images.unsplash.com/photo-1560185127-6ed189bf02f4",
  },
  {
    id: 14,
    name: "ПлиткаPro",
    city: "Шымкент",
    category: "real-estate",
    description: "Плиточные работы, ванные комнаты, кухни.",
    services: ["Отделка"],
    rating: 4.5,
    reviews: 71,
    priceFrom: 13000,
    priceTo: 32000,
    licensed: false,
    years: 7,
    responseDays: 1,
    availabilityDays: 4,
    website: "https://example.com/re4",
    phone: "+7 700 123 45 00",
    tags: ["Замер бесплатно"],
    imageUrl: "https://images.unsplash.com/photo-1516116216624-53e697fedbea",
  },
  {
    id: 15,
    name: "Двери&Пол",
    city: "Караганда",
    category: "real-estate",
    description: "Ламинат, паркет, двери — монтаж и ремонт.",
    services: ["Отделка", "Окна и двери"],
    rating: 4.1,
    reviews: 39,
    priceFrom: 9000,
    priceTo: 24000,
    licensed: false,
    years: 5,
    responseDays: 2,
    availabilityDays: 6,
    website: "https://example.com/re5",
    phone: "+7 701 555 66 44",
    tags: ["Недорого"],
    imageUrl: "https://images.unsplash.com/photo-1581093588401-16e7c98a8f17",
  },
  {
    id: 16,
    name: "CleanRoom",
    city: "Алматы",
    category: "real-estate",
    description: "Клининг после ремонта и генеральная уборка.",
    services: ["Клининг"],
    rating: 4.6,
    reviews: 110,
    priceFrom: 10000,
    priceTo: 30000,
    licensed: true,
    years: 4,
    responseDays: 1,
    availabilityDays: 2,
    website: "https://example.com/re6",
    phone: "+7 700 600 70 80",
    tags: ["Эко-средства"],
    imageUrl: "https://images.unsplash.com/photo-1600585154526-990dced4db0d",
  },
  {
    id: 17,
    name: "DesignLab KZ",
    city: "Астана",
    category: "real-estate",
    description: "Дизайн-проект квартир с визуализациями.",
    services: ["Дизайн‑проект"],
    rating: 4.7,
    reviews: 77,
    priceFrom: 18000,
    priceTo: 45000,
    licensed: true,
    years: 6,
    responseDays: 2,
    availabilityDays: 14,
    website: "https://example.com/re7",
    phone: "+7 700 444 33 22",
    tags: ["3D‑визуализация"],
    imageUrl: "https://images.unsplash.com/photo-1560185127-6ed189bf02f4",
  },
  // --- Additional automobiles to reach >=10 ---
  {
    id: 18,
    name: "AutoFix Center",
    city: "Алматы",
    category: "automobiles",
    description: "Комплексный ремонт и обслуживание авто.",
    services: ["ТО", "Диагностика"],
    rating: 4.4,
    reviews: 120,
    priceFrom: 8000,
    priceTo: 40000,
    licensed: true,
    years: 8,
    responseDays: 1,
    availabilityDays: 3,
    website: "https://example.com/auto4",
    phone: "+7 777 111 22 44",
    tags: ["Гарантия"],
    imageUrl: "https://images.unsplash.com/photo-1515920010264-05a0f6a4c28f",
  },
  {
    id: 19,
    name: "DetailPro Astana",
    city: "Астана",
    category: "automobiles",
    description: "Детейлинг: полировка, керамика, салон.",
    services: ["Детейлинг", "Керамика"],
    rating: 4.8,
    reviews: 98,
    priceFrom: 20000,
    priceTo: 90000,
    licensed: false,
    years: 5,
    responseDays: 1,
    availabilityDays: 5,
    website: "https://example.com/auto5",
    phone: "+7 700 333 22 11",
    tags: ["Запись онлайн"],
    imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70",
  },
  {
    id: 20,
    name: "ШинСервис 24",
    city: "Караганда",
    category: "automobiles",
    description: "Шиномонтаж круглосуточно, балансировка.",
    services: ["Шиномонтаж", "Балансировка"],
    rating: 4.2,
    reviews: 66,
    priceFrom: 4000,
    priceTo: 20000,
    licensed: false,
    years: 10,
    responseDays: 0,
    availabilityDays: 0,
    website: "https://example.com/auto6",
    phone: "+7 705 100 20 30",
    tags: ["24/7"],
    imageUrl: "https://images.unsplash.com/photo-1515920010264-05a0f6a4c28f",
  },
  {
    id: 21,
    name: "Brake&Go",
    city: "Алматы",
    category: "automobiles",
    description: "Ремонт тормозной системы, колодки, диски.",
    services: ["Ходовая"],
    rating: 4.3,
    reviews: 54,
    priceFrom: 9000,
    priceTo: 35000,
    licensed: true,
    years: 7,
    responseDays: 2,
    availabilityDays: 4,
    website: "https://example.com/auto7",
    phone: "+7 777 777 77 77",
    tags: ["Оригинальные запчасти"],
    imageUrl: "https://images.unsplash.com/photo-1515920010264-05a0f6a4c28f",
  },
  {
    id: 22,
    name: "AutoDiag Pro",
    city: "Астана",
    category: "automobiles",
    description: "Компьютерная диагностика всех марок.",
    services: ["Диагностика"],
    rating: 4.6,
    reviews: 73,
    priceFrom: 7000,
    priceTo: 28000,
    licensed: true,
    years: 6,
    responseDays: 1,
    availabilityDays: 2,
    website: "https://example.com/auto8",
    phone: "+7 700 222 33 44",
    tags: ["Гарантия"],
    imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70",
  },
  {
    id: 23,
    name: "OilChange KZ",
    city: "Шымкент",
    category: "automobiles",
    description: "Замена масла и фильтров, ТО.",
    services: ["ТО"],
    rating: 4.1,
    reviews: 44,
    priceFrom: 5000,
    priceTo: 22000,
    licensed: false,
    years: 3,
    responseDays: 1,
    availabilityDays: 1,
    website: "https://example.com/auto9",
    phone: "+7 707 909 80 70",
    tags: ["Быстро"],
    imageUrl: "https://images.unsplash.com/photo-1515920010264-05a0f6a4c28f",
  },
  {
    id: 24,
    name: "CarWash Pro",
    city: "Алматы",
    category: "automobiles",
    description: "Автомойка премиум, покрытие воском.",
    services: ["Детейлинг"],
    rating: 4.0,
    reviews: 31,
    priceFrom: 3000,
    priceTo: 15000,
    licensed: false,
    years: 2,
    responseDays: 0,
    availabilityDays: 0,
    website: "https://example.com/auto10",
    phone: "+7 700 606 50 40",
    tags: ["24/7"],
    imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70",
  },
  // --- Additional other to reach >=10 ---
  {
    id: 25,
    name: "ХолодПро",
    city: "Атырау",
    category: "other",
    description: "Ремонт холодильников и кондиционеров.",
    services: ["Техника"],
    rating: 4.5,
    reviews: 59,
    priceFrom: 8000,
    priceTo: 26000,
    licensed: false,
    years: 6,
    responseDays: 1,
    availabilityDays: 2,
    website: "https://example.com/oth3",
    phone: "+7 777 808 90 10",
    tags: ["Выезд"],
    imageUrl: "https://images.unsplash.com/photo-1581093588401-16e7c98a8f17",
  },
  {
    id: 26,
    name: "Телемастер KZ",
    city: "Алматы",
    category: "other",
    description: "Ремонт телевизоров и аудиосистем на дому.",
    services: ["Техника"],
    rating: 4.2,
    reviews: 47,
    priceFrom: 6000,
    priceTo: 20000,
    licensed: false,
    years: 4,
    responseDays: 1,
    availabilityDays: 3,
    website: "https://example.com/oth4",
    phone: "+7 701 222 33 11",
    tags: ["Недорого"],
    imageUrl: "https://images.unsplash.com/photo-1516116216624-53e697fedbea",
  },
  {
    id: 27,
    name: "Электрик Сервис",
    city: "Шымкент",
    category: "other",
    description: "Мелкий бытовой ремонт электрики.",
    services: ["Электрика"],
    rating: 4.3,
    reviews: 70,
    priceFrom: 7000,
    priceTo: 19000,
    licensed: false,
    years: 5,
    responseDays: 1,
    availabilityDays: 2,
    website: "https://example.com/oth5",
    phone: "+7 777 100 20 30",
    tags: ["Срочный выезд"],
    imageUrl: "https://images.unsplash.com/photo-1516116216624-53e697fedbea",
  },
  {
    id: 28,
    name: "СантехПомощь",
    city: "Алматы",
    category: "other",
    description: "Устранение протечек, замена сантехники.",
    services: ["Сантехника"],
    rating: 4.6,
    reviews: 102,
    priceFrom: 9000,
    priceTo: 28000,
    licensed: true,
    years: 9,
    responseDays: 1,
    availabilityDays: 2,
    website: "https://example.com/oth6",
    phone: "+7 705 303 40 50",
    tags: ["Гарантия"],
    imageUrl: "https://images.unsplash.com/photo-1581090467213-8cba0e09a49a",
  },
  {
    id: 29,
    name: "МебельФикс",
    city: "Костанай",
    category: "other",
    description: "Сборка и ремонт мебели на дому.",
    services: ["Мебель"],
    rating: 4.1,
    reviews: 34,
    priceFrom: 5000,
    priceTo: 20000,
    licensed: false,
    years: 3,
    responseDays: 2,
    availabilityDays: 4,
    website: "https://example.com/oth7",
    phone: "+7 700 909 80 10",
    tags: ["Недорого"],
    imageUrl: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
  },
  {
    id: 30,
    name: "Гаджет-Мастер",
    city: "Астана",
    category: "other",
    description: "Ремонт смартфонов и ноутбуков.",
    services: ["Техника"],
    rating: 4.4,
    reviews: 90,
    priceFrom: 7000,
    priceTo: 35000,
    licensed: false,
    years: 6,
    responseDays: 1,
    availabilityDays: 3,
    website: "https://example.com/oth8",
    phone: "+7 777 600 50 40",
    tags: ["Гарантия"],
    imageUrl: "https://images.unsplash.com/photo-1516116216624-53e697fedbea",
  },
];

export const CITIES = ["Алматы", "Астана", "Шымкент", "Караганда", "Актобе", "Атырау", "Костанай"];

export const SERVICES = [
  "Ремонт под ключ",
  "Отделка",
  "Сантехника",
  "Электрика",
  "Дизайн‑проект",
  "Мебель на заказ",
  "Окна и двери",
  "Клининг",
];

export const SERVICES_AUTOMOBILES = [
  "ТО",
  "Диагностика",
  "Ходовая",
  "Детейлинг",
  "Полировка",
  "Керамика",
  "Шиномонтаж",
  "Балансировка",
];

export const SERVICES_REAL_ESTATE = [
  "Ремонт под ключ",
  "Отделка",
  "Сантехника",
  "Электрика",
  "Дизайн‑проект",
  "Клининг",
  "Окна и двери",
  "Мебель на заказ",
];

export const SERVICES_OTHER = [
  "Электрика",
  "Сантехника",
  "Техника",
  "Мебель",
];
